name       : perl-list-utilsby
version    : '0.11'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PEVANS/List-UtilsBy-0.11.tar.gz : faddf43b4bc21db8e4c0e89a26e5f23fe626cde3491ec651b6aa338627f5775a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : higher-order list utility functions
description: |
    higher-order list utility functions
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
