name       : perl-list-utilsby
version    : '0.10'
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PEVANS/List-UtilsBy-0.10.tar.gz : bed74094c625aa34a5ae94a7e1fe1856f08e1bd26b8ba152bfe7a51d3277192e
license    : GPL-2.0
component  : programming.perl
summary    : higher-order list utility functions
description: |
    higher-order list utility functions
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
