name       : perl-list-utilsby
version    : '0.12'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PEVANS/List-UtilsBy-0.12.tar.gz : fff1281fd469fe982b1a58044becfd970f313bff3a26e1c7b2b3f4c0a5ed71e0
homepage   : https://metacpan.org/pod/List::UtilsBy
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : List::UtilsBy - higher-order list utility functions
description: |
    This module provides a number of list utility functions, all of which take an initial code block to control their behaviour. They are variations on similar core perl or List::Util functions of similar names, but which use the block to control their behaviour.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
